# Generated by Django 6.0.6 on 2026-07-05 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trip",
            options={},
        ),
        migrations.AlterModelTable(
            name="trip",
            table="trips",
        ),
    ]
