# Generated by Django 6.0.6 on 2026-07-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_alter_trip_options_alter_trip_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="generate_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("generating_route", "Generating Route"),
                    ("generating_fuel_stops", "Generating Fuel Stops"),
                    ("generating_rest_stops", "Generating Rest Stops"),
                    ("generating_logs", "Generating Logs"),
                ],
                max_length=50,
            ),
        ),
    ]
