# Generated by Django 6.0.6 on 2026-07-05 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_location_options_alter_location_table_and_more"),
        ("trips", "0004_alter_trip_generate_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="curr_to_pickup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="curr_to_pickup_relation",
                to="common.locationroute",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="pickup_to_drop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pickup_to_drop_relation",
                to="common.locationroute",
            ),
        ),
    ]
