# Generated by Django 6.0.6 on 2026-07-05 13:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0005_trip_curr_to_pickup_trip_pickup_to_drop"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="start_date",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
