# Generated by Django 6.0.6 on 2026-07-05 19:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_add_location_type_stops_eld_logs"),
        ("trips", "0006_trip_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="estimated_arrival",
            field=models.DateTimeField(
                blank=True,
                help_text="Estimated wall-clock arrival at the drop-off location",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="total_distance_miles",
            field=models.FloatField(
                blank=True,
                help_text="Total trip distance in miles (both legs combined)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="total_driving_hours",
            field=models.FloatField(
                blank=True,
                help_text="Sum of all DRIVING DutyLogEntry durations",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="total_on_duty_hours",
            field=models.FloatField(
                blank=True,
                help_text="DRIVING + ON_DUTY hours (counts toward 70-hr cycle)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="total_rest_hours",
            field=models.FloatField(
                blank=True, help_text="OFF_DUTY + SLEEPER_BERTH hours", null=True
            ),
        ),
        migrations.CreateModel(
            name="TripStop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stop_type",
                    models.CharField(
                        choices=[
                            ("pickup", "Pickup"),
                            ("dropoff", "Drop-off"),
                            ("fuel", "Fuel Stop"),
                            ("rest_break", "30-Minute Rest Break"),
                            ("sleeper_reset", "10-Hour Sleeper Berth Reset"),
                            ("restart_34hr", "34-Hour Restart"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("arrival_time", models.DateTimeField()),
                ("departure_time", models.DateTimeField()),
                (
                    "duration_hours",
                    models.FloatField(
                        help_text="(departure - arrival) in hours — denormalised for fast queries"
                    ),
                ),
                (
                    "odometer_start",
                    models.FloatField(
                        default=0.0,
                        help_text="Cumulative trip miles at arrival at this stop",
                    ),
                ),
                (
                    "odometer_end",
                    models.FloatField(
                        default=0.0,
                        help_text="Cumulative trip miles at departure from this stop (= odometer_start for most stops)",
                    ),
                ),
                ("sequence", models.PositiveIntegerField(db_index=True)),
                ("remarks", models.CharField(blank=True, max_length=255)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trip_stops",
                        to="common.location",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "db_table": "trip_stops",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="DutyLogEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "duty_status",
                    models.CharField(
                        choices=[
                            ("off_duty", "Off Duty"),
                            ("sleeper_berth", "Sleeper Berth"),
                            ("driving", "Driving"),
                            ("on_duty", "On Duty (Not Driving)"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "duration_hours",
                    models.FloatField(
                        help_text="(end - start) in hours — denormalised for metrics queries"
                    ),
                ),
                ("miles_driven", models.FloatField(default=0.0)),
                (
                    "odometer_start",
                    models.FloatField(
                        default=0.0, help_text="Cumulative trip miles at segment start"
                    ),
                ),
                (
                    "odometer_end",
                    models.FloatField(
                        default=0.0, help_text="Cumulative trip miles at segment end"
                    ),
                ),
                (
                    "trip_day",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        help_text="1-indexed calendar day within the trip (used to build ELDDailyLog)",
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=255)),
                ("sequence", models.PositiveIntegerField()),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duty_log_entries",
                        to="trips.trip",
                    ),
                ),
                (
                    "trip_stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duty_entries",
                        to="trips.tripstop",
                    ),
                ),
            ],
            options={
                "db_table": "duty_log_entries",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="TripViolation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("daily_driving_limit", "Daily Driving Limit Exceeded"),
                            ("driving_window_14hr", "14-Hour Window Exceeded"),
                            ("break_required", "30-Minute Break Required"),
                            ("cycle_hours_exceeded", "70-Hour/8-Day Cycle Exceeded"),
                            ("insufficient_reset", "Insufficient 10-Hour Reset"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        help_text="Absolute timestamp within the trip when the violation was detected"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "trip_day",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Calendar day within the trip on which the violation occurs",
                        null=True,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "db_table": "trip_violations",
                "ordering": ["occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="ELDDailyLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day_number",
                    models.PositiveSmallIntegerField(
                        help_text="1-indexed day within the trip"
                    ),
                ),
                (
                    "log_date",
                    models.DateField(
                        help_text="Calendar date (midnight-to-midnight in driver's home-terminal timezone)"
                    ),
                ),
                (
                    "off_duty_hours",
                    models.FloatField(
                        default=0.0,
                        help_text="Total Off Duty hours on this calendar day",
                    ),
                ),
                (
                    "sleeper_berth_hours",
                    models.FloatField(
                        default=0.0,
                        help_text="Total Sleeper Berth hours on this calendar day",
                    ),
                ),
                (
                    "driving_hours",
                    models.FloatField(
                        default=0.0,
                        help_text="Total Driving hours on this calendar day",
                    ),
                ),
                (
                    "on_duty_hours",
                    models.FloatField(
                        default=0.0,
                        help_text="Total On Duty (Not Driving) hours on this calendar day",
                    ),
                ),
                (
                    "total_miles_driven",
                    models.FloatField(
                        default=0.0,
                        help_text="Miles driven on this calendar day (ELD sheet header)",
                    ),
                ),
                (
                    "total_on_duty_hours",
                    models.FloatField(
                        default=0.0,
                        help_text="driving_hours + on_duty_hours — counts toward 70-hr cycle",
                    ),
                ),
                ("has_violations", models.BooleanField(default=False)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eld_daily_logs",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "db_table": "eld_daily_logs",
                "ordering": ["day_number"],
                "indexes": [
                    models.Index(
                        fields=["trip", "log_date"],
                        name="eld_daily_l_trip_id_80c761_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trip", "day_number"), name="uq_eld_trip_day"
                    ),
                    models.UniqueConstraint(
                        fields=("trip", "log_date"), name="uq_eld_trip_date"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="tripstop",
            index=models.Index(
                fields=["trip", "stop_type"], name="trip_stops_trip_id_bc7c6c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tripstop",
            unique_together={("trip", "sequence")},
        ),
        migrations.AddIndex(
            model_name="dutylogentry",
            index=models.Index(
                fields=["trip", "duty_status"], name="duty_log_en_trip_id_a3c482_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dutylogentry",
            index=models.Index(
                fields=["trip", "trip_day"], name="duty_log_en_trip_id_0bd10a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dutylogentry",
            index=models.Index(
                fields=["trip", "trip_day", "duty_status"],
                name="duty_log_en_trip_id_611b89_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dutylogentry",
            unique_together={("trip", "sequence")},
        ),
    ]
