# Generated by Django 6.0.6 on 2026-07-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_add_location_type_stops_eld_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
