# Generated by Django 6.0.6 on 2026-07-05 13:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={},
        ),
        migrations.AlterModelTable(
            name="location",
            table="locations",
        ),
        migrations.CreateModel(
            name="LocationRoute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("distance", models.FloatField(help_text="Distance in meters")),
                ("time", models.FloatField(help_text="Time in milliseconds")),
                (
                    "points_encoded",
                    models.TextField(help_text="Encoded polyline string"),
                ),
                ("bbox", models.JSONField(help_text="Bounding box coordinates")),
                ("max_speed", models.FloatField(blank=True, null=True)),
                ("average_speed", models.FloatField(blank=True, null=True)),
                (
                    "end_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="location_end",
                        to="common.location",
                    ),
                ),
                (
                    "start_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="location_start",
                        to="common.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location Route",
                "verbose_name_plural": "Location Routes",
                "db_table": "location_routes",
            },
        ),
    ]
