# Generated by Django 6.0.6 on 2026-07-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_location_options_alter_location_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("waypoint", "Waypoint"),
                    ("gas_station", "Gas Station"),
                    ("motel_hotel", "Motel / Hotel"),
                    ("rest_area", "Rest Area"),
                ],
                db_index=True,
                default="waypoint",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="place_name",
            field=models.CharField(
                blank=True,
                help_text="Business name (e.g. 'Shell Station', 'Comfort Inn')",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="location",
            name="country_code",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="location",
            name="place_id",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["location_type", "latitude", "longitude"],
                name="locations_locatio_752be1_idx",
            ),
        ),
    ]
